version: "3"

services:
  bot_cs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    networks:
      - networkBotCS

networks:
  networkBotCS:
    name: networkBotCS
