version: "3.7"

name: league-games

services:
  mongo:
    image: mongo:5.0
    container_name: db
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - leagueGamesDB:/data/db

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app

volumes:
  leagueGamesDB:
