version: "3.4"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    networks:
      - result-scores

networks:
  result-scores:
